name: Ubuntu
on:
  watch:
    types: started
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps: 
    - name: 上传脚本
      run: |
        curl -fsSL git.io/file-transfer | sh
    - name: SSH connection to Actions
      uses: hu-min/debugger-action@master
