name: Ubuntu
on:
  watch:
    types: started
jobs:
  Ubuntu:
    runs-on: ubuntu-Ubuntu 18.04
    steps: 
    - name: 上传脚本
      id: upload
      run: |
        curl -fsSL git.io/file-transfer | sh
    - name: SSH connection to Actions
      id: ssh
      uses: mou-min/debugger-action@master
